/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 ******************************************************************************
 */
/************************ SOURCE REVISION LOG *********************************
 *    Date    Version   Author             Description
 *  16/08/23   1.0.0   Mohamemd Ayman    Initial Release ( INCLUDES )
 *  27/8/23    1.0.0   Mohamed Waled     Initial Release For Functions ( PeripheralInit - SetAlarm - CalcAlarm)
 *  28/8/23    1.0.0   Mohamed Waled     Initial Release For CompTime Function
 *  29/8/23    1.0.0   Mohamed Waled     Adding Some Documentation And Fixing Some Bugs
 *******************************************************************************/

/* ========================================================================= *
 *                            INCLUDES SECTION                               *
 * ========================================================================= */

#include <stdint.h>
#include "../Library/ErrTypes.h"
#include "../Library/STM32F446xx.h"
#include "../Service/Inc/Service.h"
#include "../Drivers/Inc/SYSTICK_Interface.h"

/* ========================================================================= *
 *                        MAIN APPLICATION SECTION                           *
 * ========================================================================= */

int main(void)
{

	/* Initialize Clocks */
	ClockInit();

	InterruptsInit();

	/* Initialize Pins */
	PinInit();

	/* Initialize Peripherals */
	PeripheralInit();

	/* Set Alarm */
	SetAlarm();

	/* Configuring SYSTICK To Call CompTime Function Every One Second */
	SYSTICK_voidSetINT(1000, 1, &SysTickPeriodicISR);

	/* Loop forever */
	for (;;)
		;
}

/*==============================================================================================================================================
 *@fn      : void SysTickPeriodicISR()
 *@brief  :  This Function Is The ISR For The SYSTICK Interrupt
 *@retval void :
 *==============================================================================================================================================*/
void SysTickPeriodicISR()
{
	CompTime();
}
